if(typeof window!=='undefined'){
const employees={Richard:{name:'Richard “Call Me Dick” Darling',role:'Salesperson'},Anastasia:{name:'Anastasia Ferrari',role:'Salesperson'},JeanClaude:{name:'Jean-Claude Bērziņš',role:'Salesperson'},Kevin:{name:'Kevin von Whatever',role:'Expense reporter'},Svetlana:{name:'Svetlana de Monte Carlo',role:'Manager'}};
const seed=[
 {ref:'S01',type:'Sale',who:'Richard',customer:'Marta & Oskars',project:'A',description:'Respectable relatives package',amount:1000,proposal:[50,30,20],final:[50,30,20],status:'Approved',chat:'linked'},
 {ref:'S02',type:'Sale',who:'Anastasia',customer:'Līga & Peter',project:'B',description:'University friends package',amount:2000,proposal:[50,50,0],final:[20,40,40],status:'Approved',chat:'No Telegram recipient linked'},
 {ref:'S03',type:'Sale',who:'JeanClaude',customer:'Elīna & Mark',project:'B',description:'Loud friends plus speeches',amount:1500,proposal:[20,30,50],final:[20,30,50],status:'Approved',chat:'linked'},
 {ref:'S04',type:'Sale',who:'Richard',customer:'Anna & Rihards',project:'A',description:'Proud uncle and emotional aunt',amount:1500,proposal:[30,40,30],final:[30,40,30],status:'Approved',chat:'No Telegram recipient linked'},
 {ref:'S05',type:'Sale',who:'Anastasia',customer:'Laura & Tom',project:'A',description:'Full ceremony guest team',amount:600,proposal:[40,30,30],final:null,status:'Pending approval',chat:'No Telegram recipient linked'},
 {ref:'E01',type:'Expense',who:'Kevin',project:null,proposalProject:'A',finalProject:'A',description:'Costumes for relatives',amount:120,status:'Allocated',chat:'linked'},
 {ref:'E02',type:'Expense',who:'Kevin',project:null,proposalProject:'B',finalProject:'B',description:'Transport for loud friends',amount:80,status:'Allocated',chat:'No Telegram recipient linked'},
 {ref:'E03',type:'Expense',who:'Kevin',project:null,proposalProject:'Overhead',finalProject:'Overhead',description:'Emergency underwear',amount:100,status:'Allocated',chat:'No Telegram recipient linked'},
 {ref:'E04',type:'Expense',who:'Kevin',project:null,proposalProject:'A',finalProject:'A',description:'Grandmother wig and shoes',amount:60,status:'Allocated',chat:'linked'},
 {ref:'E05',type:'Expense',who:'Kevin',project:null,proposalProject:'A',finalProject:'B',description:'Taxi for the grandmother',amount:90,status:'Allocated · changed',chat:'linked'},
 {ref:'E06',type:'Expense',who:'Kevin',project:null,proposalProject:'Overhead',finalProject:'Overhead',description:'Website hosting and bot setup',amount:60,status:'Allocated',chat:'No Telegram recipient linked'},
 {ref:'E07',type:'Expense',who:'Kevin',project:null,proposalProject:'B',finalProject:null,description:'Cake-falling insurance',amount:140,status:'Awaiting allocation',chat:'No Telegram recipient linked'}
];
let records=JSON.parse(localStorage.fiRecords||'null')||seed; let role=localStorage.fiRole||'Svetlana';
const money=n=>new Intl.NumberFormat('en-IE',{style:'currency',currency:'EUR'}).format(n||0); const el=id=>document.getElementById(id);
function calc(){let sales=records.filter(r=>r.type==='Sale'&&r.status==='Approved');let expenses=records.filter(r=>r.type==='Expense');let commission=sales.reduce((s,r)=>s+r.amount*.1,0);let overhead=expenses.filter(r=>r.finalProject==='Overhead').reduce((s,r)=>s+r.amount,0);let awaiting=expenses.filter(r=>!r.finalProject).reduce((s,r)=>s+r.amount,0);let projects={A:{sales:0,comm:0,exp:0},B:{sales:0,comm:0,exp:0}};sales.forEach(r=>{projects[r.project].sales+=r.amount;projects[r.project].comm+=r.amount*.1;});expenses.filter(r=>r.finalProject==='A'||r.finalProject==='B').forEach(r=>projects[r.finalProject].exp+=r.amount);return {sales,expenses,commission,overhead,awaiting,projects,company:sales.reduce((s,r)=>s+r.amount,0)-commission-expenses.reduce((s,r)=>s+r.amount,0)};}
function render(){let c=calc(); let roleLabel=role==='Svetlana'?'Svetlana · Manager':employees[role].name; document.querySelector('#app').innerHTML=`<main class="shell"><header class="top"><div class="brand"><span class="mark">✦</span> Friends Included <span style="font-weight:400;color:var(--muted)">/ finance desk</span></div><label class="role">Demonstration role <select id="role">${Object.entries(employees).map(([k,v])=>`<option value="${k}" ${k===role?'selected':''}>${v.name}</option>`).join('')}</select></label></header><section class="hero"><div class="hero-main"><div><div class="eyebrow">Friends Included Ltd · Day 4</div><h1>All friendships expire at checkout.</h1><p>One calm place to record the convincing relatives, loud university friends, and the expenses that keep the operation moving.</p></div><div class="links"><a href="https://t.me/" target="_blank">Telegram bot ↗</a><a href="https://docs.google.com/spreadsheets/d/1AZ__P96ArJzLLTs6kGVPPIDS8229bhYcKgGu6I8O7wk/edit?usp=sharing" target="_blank">Google Sheets ↗</a><a href="https://github.com/" target="_blank">GitHub ↗</a></div></div><div class="hero-side"><span>Live operating picture</span><strong>${money(c.company)}</strong><span>Company result after approved sales, commissions, and every recorded expense.</span></div></section><nav class="tabs"><button class="tab active" data-tab="dashboard">Dashboard</button><button class="tab" data-tab="submit">New transaction</button><button class="tab" data-tab="manager">Manager controls</button></nav><section id="view"></section><footer class="footer"><span>Fictional data · no customer payments or taxes calculated</span><span>Sync status: <b style="color:var(--green)">Ready · local records persisted</b></span></footer></main>`; el('role').onchange=e=>{role=e.target.value;localStorage.fiRole=role;render()}; document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');show(b.dataset.tab)});show('dashboard');}
function show(tab){if(tab==='dashboard')dashboard(); if(tab==='submit')submit(); if(tab==='manager')manager();}
function dashboard(){let c=calc();el('view').innerHTML=`<div class="grid"><div class="metric"><small>Approved income</small><b>${money(c.sales.reduce((s,r)=>s+r.amount,0))}</b><div class="metrics-sub"><span>Pending ${money(records.filter(r=>r.type==='Sale'&&r.status!=='Approved').reduce((s,r)=>s+r.amount,0))}</span><span>Sales</span></div></div><div class="metric"><small>Commission expense</small><b>${money(c.commission)}</b><div class="metrics-sub"><span>10% pool</span><span>Approved only</span></div></div><div class="metric"><small>Overhead</small><b>${money(c.overhead)}</b><div class="metrics-sub"><span>Company</span><span>Recorded</span></div></div><div class="metric"><small>Awaiting allocation</small><b>${money(c.awaiting)}</b><div class="metrics-sub"><span>Included in result</span><span>Pending</span></div></div></div><div class="content"><section class="panel"><div class="panel-head"><div><h2>Project results</h2><p>Approved sales less commission and allocated expenses.</p></div><span class="pill">${records.length} records</span></div><div class="grid" style="margin:0;grid-template-columns:1fr 1fr"><div class="metric"><small>Project A · Respectable Relatives</small><b>${money(c.projects.A.sales-c.projects.A.comm-c.projects.A.exp)}</b><div class="metrics-sub"><span>Sales ${money(c.projects.A.sales)}</span><span>Expenses ${money(c.projects.A.exp)}</span></div></div><div class="metric"><small>Project B · Drunk University Friends</small><b>${money(c.projects.B.sales-c.projects.B.comm-c.projects.B.exp)}</b><div class="metrics-sub"><span>Sales ${money(c.projects.B.sales)}</span><span>Expenses ${money(c.projects.B.exp)}</span></div></div></div><h3 class="section-title">Commission earned</h3><div class="table-wrap"><table class="table"><thead><tr><th>Salesperson</th><th>Share</th><th>Earned</th></tr></thead><tbody>${['Richard','Anastasia','JeanClaude'].map((n,i)=>`<tr><td>${employees[n].name}</td><td>${records.filter(r=>r.type==='Sale'&&r.status==='Approved').reduce((s,r)=>s+r.amount*.1*(r.final[i]/100),0)/c.commission*100||0}%</td><td>${money(records.filter(r=>r.type==='Sale'&&r.status==='Approved').reduce((s,r)=>s+r.amount*.1*(r.final[i]/100),0))}</td></tr>`).join('')}</tbody></table></div></section><section class="panel"><div class="panel-head"><div><h2>Recent records</h2><p>Website and Telegram submissions share these rules.</p></div></div><div class="table-wrap"><table class="table"><thead><tr><th>Ref</th><th>Type</th><th>Submitted by</th><th>Amount</th><th>Status</th></tr></thead><tbody>${records.slice().reverse().map(r=>`<tr><td class="ref">${r.ref}</td><td>${r.type}</td><td>${employees[r.who]?.name.split(' ')[0]}</td><td>${money(r.amount)}</td><td><span class="pill ${r.status.includes('Awaiting')?'await':r.status.includes('Pending')?'pending':''}">${r.status}</span></td></tr>`).join('')}</tbody></table></div></section></div>`}
function submit(){el('view').innerHTML=`<div class="content"><section class="panel"><div class="panel-head"><div><h2>Record a transaction</h2><p>Role: <b>${employees[role].name}</b>. References are unique.</p></div><span class="pill">Same rules as Telegram</span></div><div class="form"><label>Transaction type<select id="kind"><option>Sale</option><option>Expense</option></select></label><div class="form-row"><label>Reference<input id="ref" placeholder="S06 or E08"></label><label>Amount (€)<input id="amount" type="number" min="0.01" step="0.01" placeholder="0.00"></label></div><label>Description<textarea id="desc" placeholder="What was delivered or purchased?"></textarea></label><div id="dynamic"></div><button class="primary" id="save">Save transaction</button></div></section><aside class="panel"><h2>Submission rules</h2><p>Sales need a customer, project, and commission proposal totalling 100%. Expenses need a category and a proposed allocation.</p><div class="notice">Saved records remain in this browser so an instructor can refresh and continue the two-test scenario.</div><div class="notice warn">Live Telegram and Google Sheets delivery requires the server-side credentials described in the homework appendix.</div></aside></div>`;el('kind').onchange=dynamic;dynamic();el('save').onclick=save}
function dynamic(){let sale=el('kind').value==='Sale';el('dynamic').innerHTML=sale?`<div class="form-row"><label>Customer<input id="customer"></label><label>Project<select id="project"><option value="A">A · Respectable Relatives</option><option value="B">B · Drunk University Friends</option></select></label></div><div class="section-title">Proposed commission split (%)</div><div class="split"><label>Richard<input id="p0" type="number" value="0"></label><label>Anastasia<input id="p1" type="number" value="0"></label><label>Jean-Claude<input id="p2" type="number" value="0"></label></div>`:`<label>Category<select id="category"><option>Materials</option><option>Travel</option><option>Other</option></select></label><label>Proposed allocation<select id="allocation"><option value="A">A · Respectable Relatives</option><option value="B">B · Drunk University Friends</option><option value="Overhead">Company overhead</option></select></label>`}
function save(){let ref=el('ref').value.trim().toUpperCase(),amount=Number(el('amount').value),sale=el('kind').value==='Sale';if(!ref||records.some(r=>r.ref===ref)||!amount||!el('desc').value.trim()){alert('Please provide a unique reference, positive amount, and description.');return}let r={ref,type:sale?'Sale':'Expense',who:role,description:el('desc').value.trim(),amount,status:sale?'Pending approval':el('allocation').value==='Overhead'?'Allocated':'Awaiting allocation',chat:'No Telegram recipient linked'};if(sale){let p=[+el('p0').value,+el('p1').value,+el('p2').value];if(p.reduce((a,b)=>a+b,0)!==100){alert('Commission shares must total 100%.');return}Object.assign(r,{customer:el('customer').value,project:el('project').value,proposal:p,final:null})}else Object.assign(r,{proposalProject:el('allocation').value,finalProject:el('allocation').value==='Overhead'?'Overhead':null,category:el('category').value});records.push(r);localStorage.fiRecords=JSON.stringify(records);alert(`${ref} saved as ${r.status}.`);render()}
function manager(){let pending=records.filter(r=>r.status==='Pending approval'||r.status==='Awaiting allocation');el('view').innerHTML=`<div class="panel"><div class="panel-head"><div><h2>Manager controls</h2><p>Approve or correct pending proposals. Actions update the existing record exactly once.</p></div><span class="pill">${pending.length} needing attention</span></div>${pending.length?`<div class="table-wrap"><table class="table"><thead><tr><th>Ref</th><th>Proposal</th><th>Amount</th><th>Decision</th></tr></thead><tbody>${pending.map(r=>`<tr><td class="ref">${r.ref}</td><td>${r.type==='Sale'?`${r.project} · ${r.proposal.join(' / ')} split`:`${r.proposalProject} · ${r.description}`}</td><td>${money(r.amount)}</td><td><button class="action" onclick="approve('${r.ref}')">Approve</button></td></tr>`).join('')}</tbody></table></div>`:`<div class="notice">Everything is decided. New pending sales and allocations will appear here.</div>`}</div>`}
window.approve=(ref)=>{let r=records.find(x=>x.ref===ref);if(r.type==='Sale'){r.final=r.proposal;r.status='Approved'}else{r.finalProject=r.proposalProject;r.status='Allocated'}localStorage.fiRecords=JSON.stringify(records);manager()};render();
}
